name: Update Documentation

on:
  push:
    branches:
      - master  # замените на вашу основную ветку

jobs:
  update_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install Dependencies and Generate Docs
        run: |
          npm install
          npx jsdoc -c jsdoc.conf.json  # указываем конфигурационный файл

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_SECRET }}
          publish_dir: ./docs
